### ISSUE TITLE
ovirt - cluster device error

### ISSUE THREAD

**Issue by TaLoN1x** [bl4ko/netbox-ssot#121]
Hello,

On repetitive runs ovirt source integrations somehow want to create cluster devices again. I think it should edit existing ones?

The Error:
ERROR   (ovirt-test): failed to add oVirt host my-ovird-node01.local with error: unexpected status code: 400: {"asset_tag":["device with this asset tag already exists."]}

**Comment by TaLoN1x** [comment]
I suppose problem comes from the fact that I have clusters in 2 sites, I defined ClusterSite with filter, but not HostSite, as there is no specific pattern for that, doesn't it inherit Site information from the Cluster?

**Comment by bl4ko** [comment]
Devices are indexed in local inventory by [site and name](https://github.com/bl4ko/netbox-ssot/blob/431b35eccc1c9c93a045c1a7cdb76d8e251247d9/internal/netbox/inventory/inventory.go#L49) attributes. So if there is going to be the same device (same asset tag) with different sites, that is going to be two different devices in local inventory. That is the reason for the above error. I guess this happened when site for device was changed and new device with new site was not matched to existing one.

Current implementation doesn't give same site for all devices part of the same cluster. This is because cluster can be made of devices from different sites. This obviously can be changed in code, but I guess cluster can have more than one site?

**Comment by TaLoN1x** [comment]
Right, question is if I want to manage it manually within the Netbox, not to speciwy in the ssot, then sync starts to fail :/

**Comment by bl4ko** [comment]
The idea is that objects managed by the netbox-ssot shouldn't be edited by user because they have the same state as on the external apis. Otherwise on the next run the data would get rewritten to match data on external apis. 

If I understand correctly your problem is with site attribute of device/host? Why not use `source.hostSiteRelations` in yaml configuration to match host with site?

**Comment by TaLoN1x** [comment]
Ok, I manage to resole that specific issue creating a filter. Then I have another nut:

I have two identical machines in different Clusters and Different Sites but with the same name :). It is de facto synched copy. There is no way for me to define Site or Tenant based on the VM Name.

ERROR   (ovirt-test): failed to sync oVirt vm: unexpected status code: 400: {"__all__":["Constraint “virtualization_virtualmachine_unique_name_cluster_tenant” is violated."]}

**Comment by TaLoN1x** [comment]
P.S. Errors could actually tell what object are they about. It is a bit hard to drill down to, I will try to make a pull request alter on that.

**Comment by bl4ko** [comment]
Yes thats the problem because vms are only [indexed by their names](https://github.com/bl4ko/netbox-ssot/blob/431b35eccc1c9c93a045c1a7cdb76d8e251247d9/internal/netbox/inventory/inventory.go#L72). So at the moment there can't be two vms with the same name. This is a bug and I will fix it since, there can be same names within different clusters.

Also agree on more verbose log output, will try to also add because of which object the error occurred (this should be trivial fix)...

**Comment by TaLoN1x** [comment]
another bug is vcpu count. I have VMs that are 2 virtual sockets, 1 core per socket, they are created with just 1 vCPU, thus should be 2.

**Comment by bl4ko** [comment]
Thanks for reporting that, could you open separate issue
