### ISSUE TITLE
Add LXC as sources on proxmox.

### ISSUE THREAD

**Issue by crower19** [bl4ko/netbox-ssot#75]
Now, only import VM correctly. 
Would be great if can import LXC.

Thanks for your work.

**Comment by bl4ko** [comment]
Hello, thanks for pointing this out. The lxc sync has been added in [v0.4.3](https://github.com/bl4ko/netbox-ssot/releases/tag/v0.4.3). Unfortunately at the moment the interfaces of containers can't be synced, because of the missing function in the underlaying library [issue](https://github.com/luthermonson/go-proxmox/issues/135). When the issues is resolved, I will also implement this feature.

**Comment by crower19** [comment]
thanks for your effort. now works fine.
